[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
layer_1 = "https://eth-goerli.g.alchemy.com/v2/FUPg1BQW1X2VnrAef0WIwSxqGpuSZdEo"
layer_2 = "https://zksync2-testnet.zksync.dev"
